from .settings import (
    GOOGLE_CLOUD_PROJECT,
    GOOGLE_CLOUD_LOCATION,
    MODEL_A,
    MODEL_B,
    ALLOWED_UNITS,
    DEFAULT_CREDENTIALS_FILE,
)

__all__ = [
    "GOOGLE_CLOUD_PROJECT",
    "GOOGLE_CLOUD_LOCATION",
    "MODEL_A",
    "MODEL_B",
    "ALLOWED_UNITS",
    "DEFAULT_CREDENTIALS_FILE",
]
